import { spawnSync } from "node:child_process";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	renameSync,
	rmSync,
} from "node:fs";
import path from "node:path";

const generatedDirectories = {
	claude: "plugin-claude/generated",
	codex: "plugins/premind/generated",
};

const publications = Object.entries(generatedDirectories).map(([name, output]) => ({
	name,
	output,
	temporary: `${output}.tmp-${process.pid}`,
	previous: `${output}.previous-${process.pid}`,
}));
const publicationByName = new Map(publications.map((entry) => [entry.name, entry]));
const stagedPath = (publication, fileName) => {
	const directory = publicationByName.get(publication)?.temporary;
	if (!directory) throw new Error(`Unknown generated publication: ${publication}`);
	return path.join(directory, fileName);
};

const targets = [
	{
		name: "daemon",
		entrypoint: "src/daemon/index.ts",
		output: stagedPath("codex", "premind-daemon.mjs"),
		copies: [stagedPath("claude", "premind-daemon.mjs")],
		external: ["node:sqlite"],
	},
	{
		name: "codex-hook",
		entrypoint: "src/codex/hook-runner.ts",
		output: stagedPath("codex", "premind-hook.mjs"),
		copies: [],
		external: [],
	},
	{
		name: "codex-mcp",
		entrypoint: "src/codex/mcp-server.ts",
		output: stagedPath("codex", "premind-mcp.mjs"),
		copies: [],
		external: [],
	},
	{
		name: "daemon-startup",
		entrypoint: "src/shared/daemon-startup.ts",
		output: stagedPath("claude", "daemon-startup.mjs"),
		copies: [],
		external: [],
	},
].sort((left, right) => left.name.localeCompare(right.name));

const bun = process.env.BUN_BINARY ?? "bun";

const preparePublications = () => {
	for (const publication of publications) {
		rmSync(publication.temporary, { recursive: true, force: true });
		rmSync(publication.previous, { recursive: true, force: true });
		mkdirSync(publication.temporary, { recursive: true });
	}
};

const publishGeneratedDirectories = () => {
	if (process.env.PREMIND_BUILD_FAIL_BEFORE_PLUGIN_SYNC === "1") {
		throw new Error("Injected failure before generated artifact publication");
	}

	const published = [];
	try {
		for (const publication of publications) {
			if (existsSync(publication.output)) {
				renameSync(publication.output, publication.previous);
			}
			try {
				renameSync(publication.temporary, publication.output);
			} catch (error) {
				if (existsSync(publication.previous)) {
					renameSync(publication.previous, publication.output);
				}
				throw error;
			}
			published.push(publication);
		}
		for (const publication of publications) {
			rmSync(publication.previous, { recursive: true, force: true });
		}
	} catch (error) {
		for (const publication of [...published].reverse()) {
			rmSync(publication.output, { recursive: true, force: true });
			if (existsSync(publication.previous)) {
				renameSync(publication.previous, publication.output);
			}
		}
		throw error;
	}
};

preparePublications();
try {
	for (const target of targets) {
		if (!existsSync(target.entrypoint)) {
			throw new Error(`Missing runtime entrypoint: ${target.entrypoint}`);
		}

		mkdirSync(path.dirname(target.output), { recursive: true });
		const result = spawnSync(
			bun,
			[
				"build",
				target.entrypoint,
				"--target=node",
				"--format=esm",
				"--banner=// @generated by scripts/build-runtime.mjs; do not edit",
				`--outfile=${target.output}`,
				...[...target.external]
					.sort()
					.flatMap((moduleName) => ["--external", moduleName]),
			],
			{
				cwd: process.cwd(),
				env: { ...process.env, FORCE_COLOR: "0", NO_COLOR: "1" },
				stdio: "inherit",
			},
		);
		if (result.error) throw result.error;
		if (result.status !== 0) {
			throw new Error(
				`Failed to build ${target.name} (exit ${result.status ?? 1})`,
			);
		}

		const formatter = spawnSync(
			process.execPath,
			[
				path.resolve("node_modules", "@biomejs", "biome", "bin", "biome"),
				"format",
				"--write",
				target.output,
			],
			{ cwd: process.cwd(), stdio: "inherit" },
		);
		if (formatter.error) throw formatter.error;
		if (formatter.status !== 0) {
			throw new Error(
				`Failed to format ${target.name} (exit ${formatter.status ?? 1})`,
			);
		}

		for (const copy of [...target.copies].sort()) {
			mkdirSync(path.dirname(copy), { recursive: true });
			copyFileSync(target.output, copy);
		}
		process.stdout.write(`Built ${target.name}\n`);
	}
	publishGeneratedDirectories();
} finally {
	for (const publication of publications) {
		rmSync(publication.temporary, { recursive: true, force: true });
		if (existsSync(publication.previous) && !existsSync(publication.output)) {
			renameSync(publication.previous, publication.output);
		} else {
			rmSync(publication.previous, { recursive: true, force: true });
		}
	}
}
