import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, renameSync, rmSync } from "node:fs";
import path from "node:path";

const targets = [
  {
    name: "daemon",
    entrypoint: "src/daemon/index.ts",
    output: "runtime/premind-daemon.mjs",
    copies: ["plugin-claude/runtime/premind-daemon.mjs"],
    external: ["node:sqlite"],
  },
  {
    name: "codex-hook",
    entrypoint: "src/codex/hook-runner.ts",
    output: "runtime/premind-hook.mjs",
    copies: [],
    external: [],
    optional: true,
  },
  {
    name: "codex-mcp",
    entrypoint: "src/codex/mcp-server.ts",
    output: "runtime/premind-mcp.mjs",
    copies: [],
    external: [],
    optional: true,
  },
  {
    name: "daemon-startup",
    entrypoint: "src/shared/daemon-startup.ts",
    output: "plugin-claude/runtime/daemon-startup.mjs",
    copies: [],
    external: [],
  },
].sort((left, right) => left.output.localeCompare(right.output));

const bun = process.env.BUN_BINARY ?? "bun";
const temporaryPathFor = (filePath) => {
  const extension = path.extname(filePath);
  const stem = extension ? filePath.slice(0, -extension.length) : filePath;
  return `${stem}.tmp-${process.pid}${extension}`;
};

for (const target of targets) {
  const copies = [...target.copies].sort();
  if (!existsSync(target.entrypoint)) {
    if (!target.optional) {
      throw new Error(`Missing runtime entrypoint: ${target.entrypoint}`);
    }
    rmSync(target.output, { force: true });
    for (const copy of copies) rmSync(copy, { force: true });
    continue;
  }

  mkdirSync(path.dirname(target.output), { recursive: true });
  const temporaryOutput = temporaryPathFor(target.output);
  const temporaryCopies = copies.map(temporaryPathFor);
  rmSync(temporaryOutput, { force: true });
  for (const temporaryCopy of temporaryCopies) {
    rmSync(temporaryCopy, { force: true });
  }

  try {
    const result = spawnSync(
      bun,
      [
        "build",
        target.entrypoint,
        "--target=node",
        "--format=esm",
        "--banner=// @generated by scripts/build-runtime.mjs; do not edit",
        `--outfile=${temporaryOutput}`,
        ...[...target.external]
          .sort()
          .flatMap((moduleName) => ["--external", moduleName]),
      ],
      {
        cwd: process.cwd(),
        env: { ...process.env, FORCE_COLOR: "0", NO_COLOR: "1" },
        stdio: "inherit",
      },
    );
    if (result.error) throw result.error;
    if (result.status !== 0) {
      throw new Error(`Failed to build ${target.name} (exit ${result.status ?? 1})`);
    }

    const formatter = spawnSync(
      process.execPath,
      [
        path.resolve("node_modules", "@biomejs", "biome", "bin", "biome"),
        "format",
        "--write",
        temporaryOutput,
      ],
      { cwd: process.cwd(), stdio: "inherit" },
    );
    if (formatter.error) throw formatter.error;
    if (formatter.status !== 0) {
      throw new Error(
        `Failed to format ${target.name} (exit ${formatter.status ?? 1})`,
      );
    }

    renameSync(temporaryOutput, target.output);
    for (const [index, copy] of copies.entries()) {
      mkdirSync(path.dirname(copy), { recursive: true });
      copyFileSync(target.output, temporaryCopies[index]);
      renameSync(temporaryCopies[index], copy);
    }
  } finally {
    rmSync(temporaryOutput, { force: true });
    for (const temporaryCopy of temporaryCopies) {
      rmSync(temporaryCopy, { force: true });
    }
  }
  process.stdout.write(`Built ${target.name}: ${target.output}\n`);
}
