import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { codexMcpTools } from "../src/codex/mcp-server.ts";
import {
	generatedCodexSkillFiles,
	generatePremindSkillMarkdown,
} from "./generate-premind-skills.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("generated Codex skill files are current in both plugin leaves", () => {
	const files = generatedCodexSkillFiles();
	assert.equal(files.length, 6);
	for (const file of files) {
		assert.equal(
			readFileSync(path.join(root, file.path), "utf8"),
			file.content,
		);
		assert.match(
			file.content,
			/Generated by scripts\/generate-premind-skills\.ts/,
		);
	}
	assert.equal(generatePremindSkillMarkdown(), generatePremindSkillMarkdown());
});

test("Codex entry point routes only the relevant task to each reference", () => {
	const entry = generatePremindSkillMarkdown();
	assert.match(
		entry,
		/^---\nname: premind\ndescription: Use when .*Premind.*\n---\n/,
	);
	assert.match(
		entry,
		/For PR tracking.*read \[subscriptions\]\(references\/subscriptions\.md\)/,
	);
	assert.match(
		entry,
		/For a Premind reminder.*read \[reminders\]\(references\/reminders\.md\)/,
	);
	assert.doesNotMatch(entry, /premind_subscribe|premind_activate_worktree/);
});

test("Codex reference names follow advertised MCP tools and preserve safety guidance", () => {
	const files = generatedCodexSkillFiles();
	const subscriptions = files.find(
		(file) =>
			file.path ===
			"plugins/premind/skills/premind/references/subscriptions.md",
	)?.content;
	const reminders = files.find(
		(file) =>
			file.path === "plugins/premind/skills/premind/references/reminders.md",
	)?.content;
	assert.ok(subscriptions);
	assert.ok(reminders);
	for (const tool of codexMcpTools) {
		assert.match(subscriptions, new RegExp(`\\b${tool.name}\\b`));
	}
	assert.match(subscriptions, /Premind session handle/);
	assert.match(subscriptions, /owner\/name/);
	assert.match(reminders, /untrusted context/);
	assert.match(reminders, /event IDs/);
	assert.match(reminders, /SessionStart.*UserPromptSubmit.*Stop/);
	assert.doesNotMatch(
		`${subscriptions}\n${reminders}`,
		/premind_set_active_checkout|premind_deliver/,
	);
});
