import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { codexMcpTools } from "../src/codex/mcp-server.ts";
import {
	generatedCodexSkillFiles,
	generatePremindSkillMarkdown,
} from "./generate-premind-skills.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("generated Codex skill files are current in both plugin leaves", () => {
	const files = generatedCodexSkillFiles();
	assert.equal(files.length, 6);
	for (const file of files) {
		assert.equal(
			readFileSync(path.join(root, file.path), "utf8"),
			file.content,
		);
		assert.match(
			file.content,
			/Generated by scripts\/generate-premind-skills\.ts/,
		);
	}
	assert.equal(generatePremindSkillMarkdown(), generatePremindSkillMarkdown());
});

test("Codex entry point routes only the relevant task to each reference", () => {
	const entry = generatePremindSkillMarkdown();
	assert.match(
		entry,
		/^---\nname: premind\ndescription: Premind pull-request tracking.*\n---\n/,
	);
	assert.match(
		entry,
		/For PR tracking.*read \[subscriptions\]\(references\/subscriptions\.md\)/,
	);
	assert.match(
		entry,
		/For a Premind reminder.*read \[reminders\]\(references\/reminders\.md\)/,
	);
	assert.doesNotMatch(entry, /premind_subscribe|premind_activate_worktree/);
});

test("Codex reference names follow advertised MCP tools and preserve safety guidance", () => {
	const files = generatedCodexSkillFiles();
	const subscriptions = files.find(
		(file) =>
			file.path ===
			"plugins/premind/skills/premind/references/subscriptions.md",
	)?.content;
	const reminders = files.find(
		(file) =>
			file.path === "plugins/premind/skills/premind/references/reminders.md",
	)?.content;
	assert.ok(subscriptions);
	assert.ok(reminders);
	for (const tool of codexMcpTools) {
		assert.match(subscriptions, new RegExp(`\\b${tool.name}\\b`));
	}
	assert.match(subscriptions, /Premind session handle/);
	assert.match(subscriptions, /owner\/name/);
	assert.match(reminders, /untrusted context/);
	assert.match(reminders, /event IDs/);
	assert.match(reminders, /SessionStart.*UserPromptSubmit.*Stop/);
	assert.doesNotMatch(
		`${subscriptions}\n${reminders}`,
		/premind_set_active_checkout|premind_deliver/,
	);
});

test("Pi and Claude skills render discoverable, host-specific references", async () => {
	const { generatedSkillFiles } = await import("./generate-premind-skills.ts");
	const metadata = JSON.parse(
		readFileSync(path.join(root, "package.json"), "utf8"),
	);
	assert.deepEqual(metadata.pi.skills, ["./skills/premind"]);
	assert.ok(metadata.files.includes("skills"));
	for (const host of ["pi", "claude"] as const) {
		const files = generatedSkillFiles(host);
		assert.equal(files.length, 3);
		const entry = files.find((file) => file.path.endsWith("/SKILL.md"));
		assert.ok(entry);
		for (const file of files) {
			assert.equal(
				readFileSync(path.join(root, file.path), "utf8"),
				file.content,
			);
		}
		for (const reference of ["subscriptions", "reminders"]) {
			assert.match(
				entry.content,
				new RegExp(`\\[${reference}\\]\\(references/${reference}\\.md\\)`),
			);
			assert.ok(
				files.some((file) => file.path.endsWith(`/references/${reference}.md`)),
			);
		}
		const subscriptions = files.find((file) =>
			file.path.endsWith("/references/subscriptions.md"),
		)?.content;
		const reminders = files.find((file) =>
			file.path.endsWith("/references/reminders.md"),
		)?.content;
		assert.ok(subscriptions);
		assert.ok(reminders);
		assert.match(subscriptions, /at the start of PR work/i);
		assert.match(subscriptions, /before reporting its URL or status/);
		assert.match(reminders, /untrusted context/);
		assert.doesNotMatch(
			subscriptions,
			/premind_activate_worktree|Premind session handle/,
		);
		if (host === "claude") {
			assert.match(subscriptions, /CLAUDE_CODE_SESSION_ID/);
			assert.match(reminders, /Stop boundary/);
			assert.doesNotMatch(subscriptions, /premind_set_active_checkout/);
		} else {
			assert.match(subscriptions, /premind_set_active_checkout/);
			assert.match(reminders, /Pi can follow up on idle sessions/);
			assert.doesNotMatch(subscriptions, /CLAUDE_CODE_SESSION_ID/);
		}
	}
});

test("live skill evaluations cover positive triggers, selective references, and near misses", () => {
	const cases = JSON.parse(
		readFileSync(path.join(root, "scripts/premind-skill-evals.json"), "utf8"),
	) as Array<{ name: string; prompt: string; reference: string | null }>;
	assert.equal(new Set(cases.map((item) => item.name)).size, cases.length);
	assert.ok(cases.some((item) => item.reference === null));
	for (const reference of ["subscriptions.md", "reminders.md"]) {
		assert.ok(cases.some((item) => item.reference === reference));
	}
	for (const item of cases) {
		assert.ok(
			item.prompt.length > 60,
			`Expected a realistic prompt: ${item.name}`,
		);
	}
});
