import { execFileSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import path from "node:path"

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)))
const output = path.join(root, "src/shared/version.generated.ts")
const fallback = '// Regenerated by the prepack lifecycle script. Keep the fallback for local checkouts.\nexport const PREMIND_BUILD_COMMIT = "------"\n'

if (process.argv[2] === "--restore") {
  writeFileSync(output, fallback)
  process.exit(0)
}

const commit = execFileSync("git", ["rev-parse", "--short=6", "HEAD"], {
  cwd: root,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "ignore"],
}).trim()
if (!/^[0-9a-f]{6}$/i.test(commit)) throw new Error("Unable to determine the six-character premind commit")

writeFileSync(output, `// Generated by npm prepack.\nexport const PREMIND_BUILD_COMMIT = "${commit}"\n`)
